<?php

namespace ContactListBundle\Repository;

use ContactListBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    public function findAddressByIdWithUser($id, User $user)
    {
        $user_id = $user->getId();
        $query = $this->getEntityManager()->createQuery('SELECT a FROM ContactListBundle:Address a WHERE a.user = :user_id AND a.id =:id');
        $query->setParameters(['id' => $id, 'user_id' => $user_id]);
        return $query->getSingleResult();
    }

    public function findAddressByUser(User $user)
    {
        $id = $user->getId();
        $query = $this->getEntityManager()->createQuery('SELECT a FROM ContactListBundle:Address a WHERE a.user = :user');
        $query->setParameter('user',$id);
        return $query->getResult();
    }
}
