<?php

namespace ContactListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
    public function findAddressByIdWithUserId($id, $user_id)
    {
        $query = $this->getEntityManager()->createQuery('SELECT a FROM ContactListBundle:Address a WHERE a.user = :user_id AND a.id =:id');
        $query->setParameters(['id' => $id, 'user_id' => $user_id]);
        return $query->getSingleResult();
    }

    public function findAddressByUserId($id)
    {
        $query = $this->getEntityManager()->createQuery('SELECT a FROM ContactListBundle:Address a WHERE a.user = :user');
        $query->setParameter('user',$id);
        return $query->getResult();
    }
}
