<?php

namespace ContactListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    public function findEmailByIdWithUserId($id, $user_id)
    {
        $query = $this->getEntityManager()->createQuery('SELECT e FROM ContactListBundle:EmailPerson e WHERE e.user = :user_id AND e.id =:id');
        $query->setParameters(['id' => $id, 'user_id' => $user_id]);
        return $query->getSingleResult();
    }

    public function findEmailByUserId($id)
    {
        $query = $this->getEntityManager()->createQuery('SELECT e FROM ContactListBundle:EmailPerson e WHERE e.user = :user');
        $query->setParameter('user',$id);
        return $query->getResult();
    }
}
