<?php

namespace ContactListBundle\Repository;

use ContactListBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends EntityRepository
{
    public function findGroupByIdWithUser($id, User $user)
    {
        $user_id = $user->getId();
        $query = $this->getEntityManager()->createQuery('SELECT g FROM ContactListBundle:GroupsPerson g WHERE g.user = :user_id AND g.id =:id');
        $query->setParameters(['id' => $id, 'user_id' => $user_id]);
        return $query->getSingleResult();
    }

    public function findGroupsByUser(User $user)
    {
        $id = $user->getId();
        $query = $this->getEntityManager()->createQuery('SELECT g FROM ContactListBundle:GroupsPerson g WHERE g.user = :user');
        $query->setParameter('user',$id);
        return $query->getResult();
    }
}
