<?php

namespace ContactListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends EntityRepository
{
    public function findPhoneByIdWithUserId($id, $user_id)
    {
        $query = $this->getEntityManager()->createQuery('SELECT p FROM ContactListBundle:Phone p WHERE p.user = :user_id AND p.id =:id');
        $query->setParameters(['id' => $id, 'user_id' => $user_id]);
        return $query->getSingleResult();
    }

    public function findPhoneByUserId($id)
    {
        $query = $this->getEntityManager()->createQuery('SELECT p FROM ContactListBundle:Phone p WHERE p.user = :user');
        $query->setParameter('user',$id);
        return $query->getResult();
    }
}
