<?php

namespace ContactListBundle\Repository;

use ContactListBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends EntityRepository
{
    public function findPhoneByIdWithUser($id, User $user)
    {
        $user_id = $user->getId();
        $query = $this->getEntityManager()->createQuery('SELECT p FROM ContactListBundle:Phone p WHERE p.user = :user_id AND p.id =:id');
        $query->setParameters(['id' => $id, 'user_id' => $user_id]);
        return $query->getSingleResult();
    }

    public function findPhoneByUser(User $user)
    {
        $id = $user->getId();
        $query = $this->getEntityManager()->createQuery('SELECT p FROM ContactListBundle:Phone p WHERE p.user = :user');
        $query->setParameter('user',$id);
        return $query->getResult();
    }
}
